---
- hosts: 192.168.75.132
  remote_user: root
  tasks:
  - name: nginx config
    template: src=/pbs/7/apache/nginx.conf dest=/etc/nginx/nginx.conf
  - name : apache config
    template: src=/pbs/7/apache/httpd.conf dest=/etc/httpd/conf/httpd.conf