---
- hosts: 192.168.75.132
  remote_user: root
  tasks:
  - name: nginx config
    template: src=/pbs/3/nginx.conf dest=/etc/nginx/nginx.conf

  - name: nginx autostart
    shell: chkconfig nginx on

  - name: nginx start
    shell: service nginx start

  - name: apache config
    template: src=/pbs/3/httpd.conf dest=/etc/httpd/conf/httpd.conf

  - name: apache autostart
    shell: chkconfig httpd on

  - name: apache start
    shell: service httpd start

  - name: mysql autostart
    shell: chkconfig mysqld on

  - name: mysql start
    shell: service mysqld start