---
- hosts: 192.168.75.132
  remote_user: root
  tasks:
#  - name: download wp
#    get_url: url=https://wordpress.org/latest.tar.gz dest=/tmp/wp.tar.gz
  - name: unpack
    unarchive: src=https://wordpress.org/latest.tar.gz dest=/ copy=no